//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/ObjectPreviewer/ObjectPreviewerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ObjectPreviewerInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ObjectPreviewerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ObjectPreviewerInputAction"",
    ""maps"": [
        {
            ""name"": ""ObjectPreviewerActionMap"",
            ""id"": ""5c842c7d-a77b-45d6-be34-e72aa2091b47"",
            ""actions"": [
                {
                    ""name"": ""OrbitKeyboard"",
                    ""type"": ""Value"",
                    ""id"": ""30fad6a8-af5d-4e75-8017-bf9cb9a56ae5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""ScaleVector2(x=5,y=5)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OrbitMouseActivation"",
                    ""type"": ""Button"",
                    ""id"": ""6402a5b8-866e-4f46-b6fa-fcfbc6ac38a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OrbitMouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6613cc49-0788-4942-a2fd-3cd8b5525d11"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DollyMouse"",
                    ""type"": ""Value"",
                    ""id"": ""db6a614c-dfc4-4d99-81e8-2c29a92fbc7f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DollyTouch1"",
                    ""type"": ""Value"",
                    ""id"": ""39dbe990-12ee-4986-875b-e0bb99063510"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DollyTouch2"",
                    ""type"": ""Value"",
                    ""id"": ""b4ea592e-b090-41c0-b475-9cbc0e04d866"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DollyTouch2Activation"",
                    ""type"": ""Button"",
                    ""id"": ""8d057f34-a7ca-42a5-a246-815818c35645"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e98b2105-2a41-4e75-873e-3e5fecfa66fe"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""706c6b8d-76a7-417b-977c-3707409715bb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6c8c0033-deb2-42b0-9fce-ccd8559fad43"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a675c093-d021-4203-b103-b2ff6b4496a1"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bd5abb6c-a82e-4460-9f4e-299e8fe62c7f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1a16395c-9148-4963-8b0b-a0520095f51f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6e6a241e-5f86-4e2c-89df-e41c2f09b8f2"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9c76bdf6-7967-4b28-8356-6e457db428d7"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2a5b8ec5-f78d-493e-ada4-6047ec759c9c"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1517b28d-7cc8-4b92-bac5-65d8a81f4435"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitKeyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9a3c704b-6709-4142-ae97-5791ca462b3e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press,MultiTap(tapTime=0.1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitMouseActivation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0910ef66-93e0-4a96-9dd9-5f8619a9a948"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": ""Press,MultiTap(tapTime=0.1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitMouseActivation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e94f569c-ddca-42a0-87fd-68c71d4f769d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd5bbba9-70ea-4461-8029-0e1e64564222"",
                    ""path"": ""<Touchscreen>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrbitMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cac191ea-a3a1-4128-b160-b0d862d69b38"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.5,y=0.5)"",
                    ""groups"": """",
                    ""action"": ""DollyMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20e9991b-63ec-4036-8dc9-9d5add2753b7"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DollyTouch1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c428012-4898-456b-9256-d13b6b2fc8be"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DollyTouch2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d742e126-a072-4522-ae6e-3af907af35a0"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DollyTouch2Activation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ObjectPreviewerActionMap
        m_ObjectPreviewerActionMap = asset.FindActionMap("ObjectPreviewerActionMap", throwIfNotFound: true);
        m_ObjectPreviewerActionMap_OrbitKeyboard = m_ObjectPreviewerActionMap.FindAction("OrbitKeyboard", throwIfNotFound: true);
        m_ObjectPreviewerActionMap_OrbitMouseActivation = m_ObjectPreviewerActionMap.FindAction("OrbitMouseActivation", throwIfNotFound: true);
        m_ObjectPreviewerActionMap_OrbitMouse = m_ObjectPreviewerActionMap.FindAction("OrbitMouse", throwIfNotFound: true);
        m_ObjectPreviewerActionMap_DollyMouse = m_ObjectPreviewerActionMap.FindAction("DollyMouse", throwIfNotFound: true);
        m_ObjectPreviewerActionMap_DollyTouch1 = m_ObjectPreviewerActionMap.FindAction("DollyTouch1", throwIfNotFound: true);
        m_ObjectPreviewerActionMap_DollyTouch2 = m_ObjectPreviewerActionMap.FindAction("DollyTouch2", throwIfNotFound: true);
        m_ObjectPreviewerActionMap_DollyTouch2Activation = m_ObjectPreviewerActionMap.FindAction("DollyTouch2Activation", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ObjectPreviewerActionMap
    private readonly InputActionMap m_ObjectPreviewerActionMap;
    private List<IObjectPreviewerActionMapActions> m_ObjectPreviewerActionMapActionsCallbackInterfaces = new List<IObjectPreviewerActionMapActions>();
    private readonly InputAction m_ObjectPreviewerActionMap_OrbitKeyboard;
    private readonly InputAction m_ObjectPreviewerActionMap_OrbitMouseActivation;
    private readonly InputAction m_ObjectPreviewerActionMap_OrbitMouse;
    private readonly InputAction m_ObjectPreviewerActionMap_DollyMouse;
    private readonly InputAction m_ObjectPreviewerActionMap_DollyTouch1;
    private readonly InputAction m_ObjectPreviewerActionMap_DollyTouch2;
    private readonly InputAction m_ObjectPreviewerActionMap_DollyTouch2Activation;
    public struct ObjectPreviewerActionMapActions
    {
        private @ObjectPreviewerInputAction m_Wrapper;
        public ObjectPreviewerActionMapActions(@ObjectPreviewerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @OrbitKeyboard => m_Wrapper.m_ObjectPreviewerActionMap_OrbitKeyboard;
        public InputAction @OrbitMouseActivation => m_Wrapper.m_ObjectPreviewerActionMap_OrbitMouseActivation;
        public InputAction @OrbitMouse => m_Wrapper.m_ObjectPreviewerActionMap_OrbitMouse;
        public InputAction @DollyMouse => m_Wrapper.m_ObjectPreviewerActionMap_DollyMouse;
        public InputAction @DollyTouch1 => m_Wrapper.m_ObjectPreviewerActionMap_DollyTouch1;
        public InputAction @DollyTouch2 => m_Wrapper.m_ObjectPreviewerActionMap_DollyTouch2;
        public InputAction @DollyTouch2Activation => m_Wrapper.m_ObjectPreviewerActionMap_DollyTouch2Activation;
        public InputActionMap Get() { return m_Wrapper.m_ObjectPreviewerActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ObjectPreviewerActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IObjectPreviewerActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_ObjectPreviewerActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ObjectPreviewerActionMapActionsCallbackInterfaces.Add(instance);
            @OrbitKeyboard.started += instance.OnOrbitKeyboard;
            @OrbitKeyboard.performed += instance.OnOrbitKeyboard;
            @OrbitKeyboard.canceled += instance.OnOrbitKeyboard;
            @OrbitMouseActivation.started += instance.OnOrbitMouseActivation;
            @OrbitMouseActivation.performed += instance.OnOrbitMouseActivation;
            @OrbitMouseActivation.canceled += instance.OnOrbitMouseActivation;
            @OrbitMouse.started += instance.OnOrbitMouse;
            @OrbitMouse.performed += instance.OnOrbitMouse;
            @OrbitMouse.canceled += instance.OnOrbitMouse;
            @DollyMouse.started += instance.OnDollyMouse;
            @DollyMouse.performed += instance.OnDollyMouse;
            @DollyMouse.canceled += instance.OnDollyMouse;
            @DollyTouch1.started += instance.OnDollyTouch1;
            @DollyTouch1.performed += instance.OnDollyTouch1;
            @DollyTouch1.canceled += instance.OnDollyTouch1;
            @DollyTouch2.started += instance.OnDollyTouch2;
            @DollyTouch2.performed += instance.OnDollyTouch2;
            @DollyTouch2.canceled += instance.OnDollyTouch2;
            @DollyTouch2Activation.started += instance.OnDollyTouch2Activation;
            @DollyTouch2Activation.performed += instance.OnDollyTouch2Activation;
            @DollyTouch2Activation.canceled += instance.OnDollyTouch2Activation;
        }

        private void UnregisterCallbacks(IObjectPreviewerActionMapActions instance)
        {
            @OrbitKeyboard.started -= instance.OnOrbitKeyboard;
            @OrbitKeyboard.performed -= instance.OnOrbitKeyboard;
            @OrbitKeyboard.canceled -= instance.OnOrbitKeyboard;
            @OrbitMouseActivation.started -= instance.OnOrbitMouseActivation;
            @OrbitMouseActivation.performed -= instance.OnOrbitMouseActivation;
            @OrbitMouseActivation.canceled -= instance.OnOrbitMouseActivation;
            @OrbitMouse.started -= instance.OnOrbitMouse;
            @OrbitMouse.performed -= instance.OnOrbitMouse;
            @OrbitMouse.canceled -= instance.OnOrbitMouse;
            @DollyMouse.started -= instance.OnDollyMouse;
            @DollyMouse.performed -= instance.OnDollyMouse;
            @DollyMouse.canceled -= instance.OnDollyMouse;
            @DollyTouch1.started -= instance.OnDollyTouch1;
            @DollyTouch1.performed -= instance.OnDollyTouch1;
            @DollyTouch1.canceled -= instance.OnDollyTouch1;
            @DollyTouch2.started -= instance.OnDollyTouch2;
            @DollyTouch2.performed -= instance.OnDollyTouch2;
            @DollyTouch2.canceled -= instance.OnDollyTouch2;
            @DollyTouch2Activation.started -= instance.OnDollyTouch2Activation;
            @DollyTouch2Activation.performed -= instance.OnDollyTouch2Activation;
            @DollyTouch2Activation.canceled -= instance.OnDollyTouch2Activation;
        }

        public void RemoveCallbacks(IObjectPreviewerActionMapActions instance)
        {
            if (m_Wrapper.m_ObjectPreviewerActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IObjectPreviewerActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_ObjectPreviewerActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ObjectPreviewerActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ObjectPreviewerActionMapActions @ObjectPreviewerActionMap => new ObjectPreviewerActionMapActions(this);
    public interface IObjectPreviewerActionMapActions
    {
        void OnOrbitKeyboard(InputAction.CallbackContext context);
        void OnOrbitMouseActivation(InputAction.CallbackContext context);
        void OnOrbitMouse(InputAction.CallbackContext context);
        void OnDollyMouse(InputAction.CallbackContext context);
        void OnDollyTouch1(InputAction.CallbackContext context);
        void OnDollyTouch2(InputAction.CallbackContext context);
        void OnDollyTouch2Activation(InputAction.CallbackContext context);
    }
}
